baseURL = "https://albumers.org/"
themesDir = "themes"
languageCode = "es"
title = "ALBUMERS - Gente que habla de los álbumes que les cambiaron la vida"
theme = [
  "fractal-forest",
  "after-dark"
]
#Disable comments by leaving disqusShortname empty
disqusShortname = ""
enableRSS = true
noindex = false
enableRobotsTXT = true
canonifyURLs = true
crossorigin = "anonymous" # Optional, sets CORS attribute
enableEmoji = true

footnoteReturnLinkContents = "↩" # Provides a nicer footnote return link

[params]
	name = "Willer"
	author = "Willer"
  hide_author = true
	description = "La comunidad de músicos habla del disco que les marcó para siempre"
	keywords = [
  		"discos",
  		"LP",
  		"música",
  		"entrevistas música",
  		"disco que cambia la vida"
	]

[frontmatter]
  date = ["date", "publishDate", "lastmod"]
  lastmod = [":git", "lastmod", "date", "publishDate"]
  publishDate = ["publishDate", "date"]
  expiryDate = ["expiryDate"]

[sitemap]
	filename = "sitemap.xml"

[taxonomies]
	tag = ""
  category = "true"
	preserveTaxonomyNames = true

[related]
	threshold = 80
	includeNewer = false
	toLower = false

	[[related.indices]]
		name = "keywords"
		weight = 150
	[[related.indices]]
		name  = "author"
		toLower = true
		weight = 30
	[[related.indices]]
		name  = "tags"
		weight = 100
	[[related.indices]]
		name  = "date"
		weight = 10
		pattern = "2006"

[params.modules.fractal_forest]
  enabled = true # Optional, set false to disable module
  decoders = ["bpgdec8a"] # Optional, 8-bit javascript decoder with animation
  
[outputs]
  home = ["HTML", "RSS", "JSON"]
  section = ["HTML", "RSS", "JSON"]
  
[[menu.main]]
  name = "Gente"
  weight = 1
  identifier = "home"
  url = "/"
[[menu.main]]
  name = "Buscar"
  weight = 2
  identifier = "search"
  url = "/search/"
[[menu.main]]
  name = "Info"
  weight = 3
  identifier = "info"
  url = "/page/info/"
[[menu.main]]
  name = "Contacto"
  weight = 4
  identifier = "contact"
  url = "/contact/form/"